# -*- coding: utf-8 -*-
"""Tarea12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zHLGagNoITd7GFWTKcEmeDPSWb8o_OeQ

# Clase: Booleanos y Ciclo `while` en Python

## ¿Qué es un valor booleano?
Los **booleanos** son un tipo de dato que representan valores de verdad, es decir si algo es verdadero o falso. Cundo usamos en el `if` la condicion tomaba un valor de verdad y dependiendo de su valor realizabamos alguna acción; es decir, los usamos para tomar decisiones en los programas.. En python tendremos los valores `True` para el valor de verdadero y `False` para el valor de falso.
"""

a = True
b = False
print("a:", a)
print("b:", b)

"""Nota que pasa si mandamos a pantalla condiciones parecidas a las que usamos en los ejercicios de las condicionales."""

print("Ejemplo uno: ",5<6)
print("Ejemplo dos: ",5>6)
print("Ejemplo tres: ",5==6)

"""## **Ciclo `while`**



El ciclo `while` repite un bloque **mientras** una condición sea verdadera.
"""

#Ejemplo:

#Definimos una variable llamada contador con el valor de 1.
contador = 1

#Mientras la variable tenga un valor menor a 5 vamos a repetir el código siguiente.
while contador < 5:
    #Mandamos a pantalla Contador seguido del valor que tiene la varibale contador.
    print("Contador:", contador)
    #Aumentamos el valor de contador
    contador = contador + 1

"""Nota que en el código pasado dentro del while la condición que se está evaluando es si el valor de la variable `contador` es menor a 5; y justo ese es el valor booleano, mientras sea cierto el valor de `contador < 5` es `True`; en el momento en que no se cumpla el valor de `contador < 5` será `False`.

Veamos otro ejmeplo, pero ahora le pasaremos explicitamente un valor boolenao a la condición del while.
"""

#Definimos una variable llamada activo con el valor boolenao True
activo = True
#Definimos una variable llamada número con el valor 0
numero = 0

#Mientras la variable activo tenga el valor de True realiza el siguiente código.
while activo:
    #Manda a pantalla Numero seguido del valor de la variable número.
    print("Número:", numero)
    #Aumenta el valor de la variable número en uno.
    numero = numero + 1
    #Si el valor de la variable numero es igual a 4 realiza lo siguiente.
    if numero == 4:
        #Cambia el valor de la varibale activo a False.
        activo = False

"""## **Ejercicios:**

***Intrucciones:*** Realiza el código que haga lo solicitado en cada ejercicios; igual que en los códigos de ejemplo agrega comentarios que explica con tus palabras que es lo que está realizando cada línea de código (recuerda que los comentarios se ponen con un "#").

1. Usa un ciclo `while` para imprimir los números del 1 al 10.
"""

#Realiza el ejercicio 1.
contador = 1
while contador <= 5:
 print("Contador:", contador)
 contador += 1 # incrementa en 1

"""2. Crea una variable booleana llamada `sigue` y úsala para controlar un ciclo que imprima "Hola" 5 veces.

"""

#Realiza el ejercicio 2.
sigue = True
contador = 0
while sigue:
    print("Hola")
    contador += 1
    if contador == 5:
        sigue = False

"""3. Escribe un `while` que imprima solo números pares hasta llegar al 20.

"""

#Realiza el ejercicio 3.
num = 2
while num <= 20:
    print(num)
    num += 2

"""4. Crea un programa que pida al usuario una contraseña usando `input()` repita mientras la contraseña sea incorrecta. La contraseña correcta es "python123".

"""

#Realiza el ejercicio 4.
clave_correcta = "python123"
clave = input("Ingresa la contraseña: ")
while clave != clave_correcta:
    print("Contraseña incorrecta. Intenta de nuevo.")
    clave = input("Ingresa la contraseña: ")
print("Acceso concedido")