# -*- coding: utf-8 -*-
"""Tarea_11 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hjUH8H0O9bId-WyYWODL-eSXciVzWRL5

# Tarea: Uso de Condicionales (if / else)

## Parte 1: Condicionales en la vida diaria
Escribe 3 oraciones de situaciones reales donde usarías un "si... entonces...".

Ejemplo:
Si me despierto tarde, entonces llego tarde a la escuela.

1.Si termino mi tarea temprano, entonces puedo jugar videojuegos.

2.Si hace mucho frío, entonces me pongo una chamarra.

3.Si estudio antes del examen, entonces me va mejor en la prueba.

## Parte 2: Explicación de la importancia de las condicionales
Explica 4 ejemplos donde se vea por qué son necesarias las condicionales.

Ejemplo modelo:


*   Situación: Decidir si llevo paraguas.
*   Condición: Si está lloviendo.
*   Si se cumple: Llevo paraguas.
*   Si no se cumple: Salgo sin paraguas.



1.
*   Situación:Elegir qué ropa usar.
*   Condición:Si hace frío.
*   Si se cumple:Entonces me pongo una chamarra.
*   Si no se cumple:No paso frío durante el día.

2.
*   Situación:decidir si puedo salir a jugar
*   Condición:si termino mi tarea
*   Si se cumple:puedo salir a jugar con mis amigas
*   Si no se cumple:me divierto sin descuidar mis estudios

3.
*   Situación:elegir si cargo mi celular
*   Condición:si tiene el 20 de bateria
*   Si se cumple:durara el resto del dia
*   Si no se cumple:se terminara la bateria

4.
*   Situación:ver si puedo comer un postre
*   Condición:si termino toda mi comida
*   Si se cumple:comere postre
*   Si no se cumple:no comere postre

## Parte 3: Condicionales en Python

### Ejercicio 1
Pide la hora (0-23). Si es menor que 12 muestra 'Es mañana', si no 'Es tarde o noche'.
"""

# Escribe tu código aquí
hora = int(input("Ingresa la hora (0-23): "))

if hora < 12:
    print("Es mañana")
else:
    print("Es tarde o noche")

"""### Ejercicio 2
Pide dos números y muestra cuál es mayor o si son iguales.

"""

# Escribe tu código aquí
num1 = float(input("Ingresa el primer número: "))
num2 = float(input("Ingresa el segundo número: "))

if num1 > num2:
    print("El primer número es mayor.")
elif num2 > num1:
    print("El segundo número es mayor.")
else:
    print("Los dos números son iguales.")

"""### Ejercicio 3
Pide un número entero y muestra si es par o impar.

"""

# Escribe tu código aquí
num = int(input("Ingresa un número entero: "))

if num % 2 == 0:
    print("El número es par.")
else:
    print("El número es impar.")